### ISSUE TITLE
License

### ISSUE THREAD

**Issue by linusg** [tc39/proposal-math-sum#15]
This repo seems to be missing a license. For the spec text it probably doesn't matter too much as it will be upstreamed, but what is the license of the polyfill?

**Comment by bakkot** [comment]
I wrote it myself based on an algorithm which is more than 20 years old, so I own the copyright. [I'll make it available under MIT](https://github.com/tc39/proposal-math-sum/commit/3513d58323a1ae25560e8700aa5294500c6c9287).

**Comment by bakkot** [comment]
Hm, actually, I guess I'll [go with BSD 3-clause](https://github.com/tc39/proposal-math-sum/commit/3c56f3df9f89d862515617c7e421f51b28bb71f8) for consistency with ECMA licenses. Let me know if you need it under MIT as well though.

**Comment by ljharb** [comment]
I need it under MIT, since that's what I included in https://npmjs.com/math.sumprecise - but since that one commit will always be under MIT, it's probably fine.
