### ISSUE TITLE
Empty list sums to 0 or -0?

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-math-sum#5]
-0 is in some sense more correct, at least if you're thinking about floats: -0 is the additive identity for floats. On the other hand, this is supposed to be approximating real-number arithmetic as closely as possible, and reals do not have -0.

As a datapoint, in Python `fsum([])` gives 0, not -0.

**Comment by michaelficarra** [comment]
I prefer `-0`.

**Comment by bakkot** [comment]
`-0` it is.
